name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  # Job zum Testen der Anwendung
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

  # Job zum Bauen für Windows
  build-windows:
    needs: test
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install -r requirements.txt
        pip install pyinstaller pillow
    - name: Extract version
      id: extract_version
      shell: bash
      run: |
        VERS=$(python -c "from src.utils.version import __version__; print(__version__)")
        echo "version=$VERS" >> $GITHUB_OUTPUT
    - name: Create assets directory
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}/assets"
    - name: Create simple icon
      shell: python
      run: |
        from PIL import Image, ImageDraw
        img = Image.new('RGBA', (256, 256), color=(30, 120, 200, 255))
        draw = ImageDraw.Draw(img)
        draw.ellipse((50, 50, 206, 206), fill=(40, 160, 230, 255))
        img.save('assets/camp_icon.ico')
    - name: Manual PyInstaller Build
      run: |
        pyinstaller --clean --name="CAMP" --windowed --icon=assets/camp_icon.ico main.py
        mkdir -p dist/CAMP/config
        cp config/*.py dist/CAMP/config/
        cp -r data dist/CAMP/
    - name: Create ZIP archive
      run: |
        cd dist
        powershell Compress-Archive -Path CAMP -DestinationPath "CAMP-${{ steps.extract_version.outputs.version }}-win64.zip"
        cd ..
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: camp-windows
        path: dist/CAMP-${{ steps.extract_version.outputs.version }}-win64.zip

  # Job zum Bauen für macOS
  build-macos:
    needs: test
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install -r requirements.txt
        pip install pyinstaller pillow
    - name: Extract version
      id: extract_version
      run: |
        VERS=$(python -c "from src.utils.version import __version__; print(__version__)")
        echo "version=$VERS" >> $GITHUB_OUTPUT
    - name: Create assets directory
      run: |
        mkdir -p assets
    - name: Create simple icon
      run: |
        python -c "
        from PIL import Image, ImageDraw
        img = Image.new('RGBA', (1024, 1024), color=(30, 120, 200, 255))
        draw = ImageDraw.Draw(img)
        draw.ellipse((200, 200, 824, 824), fill=(40, 160, 230, 255))
        img.save('assets/camp_icon.png')
        "
    - name: Manual PyInstaller Build
      run: |
        pyinstaller --clean --name="CAMP" --windowed --icon=assets/camp_icon.png main.py
        mkdir -p dist/CAMP.app/Contents/Resources/config
        cp -r config/*.py dist/CAMP.app/Contents/Resources/config/
        cp -r data dist/CAMP.app/Contents/Resources/
    - name: Create DMG
      run: |
        brew install create-dmg
        mkdir -p dmg-build
        cp -r dist/CAMP.app dmg-build/
        create-dmg \
          --volname "CAMP-${{ steps.extract_version.outputs.version }}" \
          --volicon "assets/camp_icon.png" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon "CAMP.app" 150 190 \
          --app-drop-link 450 185 \
          "dist/CAMP-${{ steps.extract_version.outputs.version }}-macos.dmg" \
          "dmg-build/"
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: camp-macos
        path: dist/CAMP-${{ steps.extract_version.outputs.version }}-macos.dmg

  # Job zum Erstellen des Releases
  create-release:
    needs: [build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Extract version
      id: extract_version
      run: |
        VERS=$(python -c "from src.utils.version import __version__; print(__version__)")
        echo "version=$VERS" >> $GITHUB_OUTPUT
        echo "VERSION=$VERS" >> $GITHUB_ENV
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: camp-windows
        path: artifacts/windows
    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: camp-macos
        path: artifacts/macos
    - name: List artifacts
      run: |
        ls -la artifacts/windows
        ls -la artifacts/macos
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: CAMP v${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false
        files: |
          artifacts/windows/CAMP-${{ steps.extract_version.outputs.version }}-win64.zip
          artifacts/macos/CAMP-${{ steps.extract_version.outputs.version }}-macos.dmg
        body: |
          # CAMP v${{ steps.extract_version.outputs.version }}
          
          Release für CAMP v${{ steps.extract_version.outputs.version }}.
          
          ## Änderungen
          
          - Initiales Release
          - Automatisches Update-System
          - Windows- und macOS-Unterstützung
          
          ## Downloads
          
          - Windows: CAMP-${{ steps.extract_version.outputs.version }}-win64.zip
          - macOS: CAMP-${{ steps.extract_version.outputs.version }}-macos.dmg
          
          ## Installation
          
          ### Windows
          - Laden Sie die ZIP-Datei herunter und entpacken Sie sie
          - Führen Sie die CAMP.exe aus
          
          ### macOS
          - Laden Sie die DMG-Datei herunter und öffnen Sie sie
          - Ziehen Sie die CAMP.app in den Applications-Ordner

  # Job zum Aktualisieren der Version
  update-version:
    needs: create-release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Increment version
      run: |
        # Extrahiere aktuelle Version
        current_version=$(python -c "from src.utils.version import __version__; print(__version__)")
        
        # Teile die Version in Major, Minor und Patch auf
        IFS='.' read -r -a version_parts <<< "$current_version"
        major="${version_parts[0]}"
        minor="${version_parts[1]}"
        patch="${version_parts[2]}"
        
        # Erhöhe die Patch-Version
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
        
        # Aktualisiere die Versionsdatei
        sed -i "s/__version__ = \"$current_version\"/__version__ = \"$new_version\"/" src/utils/version.py
        
        # Aktualisiere Release-Datum
        today=$(date +%Y-%m-%d)
        sed -i "s/__release_date__ = \".*\"/__release_date__ = \"$today\"/" src/utils/version.py
        
        echo "Updated version from $current_version to $new_version"
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
    - name: Commit version update
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add src/utils/version.py
        git commit -m "Bump version to $NEW_VERSION [skip ci]"
        git push